[package]
name = "vk_infodump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
tinyfiledialogs = "3.9.0"

[dependencies.ash]
version = "0.36.0"
features = ["linked"]